version: "3.7"
services:
  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka:/bitnami
    networks:
      kafkanet:
        ipv4_address: 172.25.0.12

  filter-inference:
    image: filter_inference:0.1
    container_name: filter-inference
    volumes:
      - ./:/app
    environment:
      - BROKER=172.25.0.12:9092
      - TOPIC_IN=wikipedia_data
      - TOPIC_OUT=wikipedia_filtered
      - FILTER_PATH=./data/filter
    networks:
      kafkanet:
        ipv4_address: 172.25.0.14
    depends_on:
      - kafka

  data-origin:
    image: data_origin:0.1
    container_name: data-origin
    volumes:
      - ./:/app
    environment:
      - BROKER=172.25.0.12:9092
      - TOPIC=wikipedia_data
      - SERVER_NAME=en.wikipedia.org
      - ACTION=edit
      - VERBOSE=true
    networks:
      kafkanet:
        ipv4_address: 172.25.0.15
    depends_on:
      - kafka
    
  lr-inference:
    image: lr_inference:0.2
    container_name: lr-inference
    volumes:
      - ./:/app
    environment:
      - BROKER=172.25.0.12:9092
      - TOPIC_IN=wikipedia_data
      - TOPIC_OUT=wikipedia_bots
      - MODEL_PATH=./data/logreg_big_best
      - SAMPLING_FREQ=0.2
    networks:
      kafkanet:
        ipv4_address: 172.25.0.16
    depends_on:
      - kafka
  
  filter-training:
    image: filter_training:0.1
    container_name: filter-training
    volumes:
      - ./:/app
    environment:
      - BROKER=172.25.0.12:9092
      - TOPIC=wikipedia_bots
      - FILTER_PATH=./data/filter
    networks:
      kafkanet:
        ipv4_address: 172.25.0.17
    depends_on:
      - kafka
      - lr-inference

  data-collection:
    image: data_collection:0.1
    container_name: data-collection
    volumes:
      - ./:/app
    environment:
      - BROKER=172.25.0.12:9092
      - TOPIC=wikipedia_data
      - DEST_FOLDER=./data/csv_stream
    networks:
      kafkanet:
        ipv4_address: 172.25.0.18
    depends_on:
      - kafka
      - data-origin

networks:
  kafkanet:
    name: kafkanet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  kafka: